comment: false # Disable codecov PR comments -> leave only the checks
coverage:
    status:
        project:
            default:
                # https://docs.codecov.com/docs/commit-status#informational
                # Avoids failing on coverage decrease
                informational: true
    patch:
        default:
            informational: true
ignore:
  - "test/performance"
