
description: 'Run tests enabling coverage in certain conditions and upload coverage artifacts for later process'

inputs:
  python-version:
    description: 'Python version in which the tests was ran'
    required: true

  test-type:
    description: 'Test suite name'
    required: true

  duration:
    description: 'Show N slowest test durations (N=0 for all)'
    required: true
    default: '10'

  tests:
    description: 'Tests folder and options to run'
    required: false

  workers:
    description: 'Number of workers to run tests'
    default: auto

runs:
  using: 'composite'
  steps:
      - name: Run tests with coverage
        if: ${{ inputs.tests }}
        shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
        run: |
          pytest ${{ inputs.tests }} -rf --durations=${{ inputs.duration }} -n ${{ inputs.workers }} ${{ github.ref == 'refs/heads/develop2' && '--cov=conan --cov=conans --cov=test --cov-report=' || '' }}

      - name: Rename coverage file
        if: github.ref == 'refs/heads/develop2'
        shell: bash
        run: mv .coverage .coverage.${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.test-type }}

      - name: Upload coverage artifact
        if: github.ref == 'refs/heads/develop2'
        uses: actions/upload-artifact@v4
        with:
          name: .coverage.${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.test-type }}
          path: .coverage.${{ runner.os }}-${{ inputs.python-version }}-${{ inputs.test-type }}
          include-hidden-files: true
