name: Build Conan Binaries

on:
  workflow_call:
    inputs:
      conan_version: { required: true, type: string }
      target_sha:    { required: true, type: string }
  workflow_dispatch:
    inputs:
      conan_version: { description: Conan version to package, required: true, type: string }
      target_sha:    { description: Git SHA to package,       required: true, type: string }

permissions:
  contents: read

jobs:

  package:
    name: Package for ${{ matrix.platform }}/${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { platform: Linux,   arch: x86_64, runner: ubuntu-24.04 }
          - { platform: Windows, arch: x86_64, runner: windows-2022 }
          - { platform: Windows, arch: i686,   runner: windows-2022 }
          - { platform: Windows, arch: arm64,  runner: windows-11-arm }
          - { platform: Macos,   arch: arm64,  runner: macos-14 }
          - { platform: Macos,   arch: x86_64, runner: macos-14 }
          - { platform: Linux,   arch: arm64,  runner: ubuntu-24.04-arm }
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Generate Read-Only App Token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_RELEASE_ID }}
          private-key: ${{ secrets.GH_APP_RELEASE_PRIVATE_KEY }}
          permission-contents: read
          owner: conan-io
          repositories: |
            conan
            release-tools

      - name: Checkout release-tools
        uses: actions/checkout@v4
        with:
          repository: conan-io/release-tools
          token: ${{ steps.generate_token.outputs.token }}

      - name: Build packages
        shell: bash
        env:
          PLATFORM: ${{ matrix.platform }}
          ARCH: ${{ matrix.arch }}
        run: |
          ./jenkins/build_packages.sh "${{ inputs.conan_version || github.event.inputs.conan_version }}" \
                                      "${{ inputs.target_sha    || github.event.inputs.target_sha    }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: conan-packages-${{ matrix.platform }}-${{ matrix.arch }}
          path: dist/*
